import io
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
import pandas as pd
from app.middleware.auth import get_current_user
from app.services.data_service import data_service

router = APIRouter(prefix="/reports", tags=["Reports & Downloads"])


@router.get("/excel")
def download_excel(_=Depends(get_current_user)):
    """Download a consolidated Excel workbook with all analytics data."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        if data_service.df is not None:
            data_service.df.head(2000).to_excel(writer, sheet_name="Sales Summary", index=False)
        if data_service.segments is not None:
            data_service.segments.to_excel(writer, sheet_name="Customer Clusters", index=False)
        if data_service.forecast is not None:
            data_service.forecast.to_excel(writer, sheet_name="Demand Forecast", index=False)
        if data_service.churn_df is not None:
            data_service.churn_df.to_excel(writer, sheet_name="Churn Risk List", index=False)
        inv = data_service.calculate_inventory_metrics()
        if not inv.empty:
            inv.to_excel(writer, sheet_name="Inventory Health", index=False)

    output.seek(0)
    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=retailpulse_executive_workbook.xlsx"},
    )


@router.get("/markdown")
def download_markdown(_=Depends(get_current_user)):
    """Download a markdown executive summary report."""
    report = """# RetailPulse Corporate Executive Performance Report
## Platform Analytics Summary (2009-2011)

### 1. Key Performance Highlights
- **Total Revenue:** £17,374,804.27
- **Database Customers:** 5,878
- **Order Count:** 36,969
- **Average Order Size:** £470.00

### 2. Segment Distribution & Strategy
- **Premium Segment (4 Customers):** VIP rewards & premium channel access.
- **Loyal Segment (38 Customers):** Targeted cross-sell.
- **Regular Segment (3,838 Customers):** Seasonal promo push.
- **At Risk Segment (1,998 Customers):** Reactivation coupon push.

### 3. Inventory Stock Alerts
- **Safety Stock Thresholds:** Monitored over 4,600 unique SKUs.
- **Stock Alert Statuses:** Generated safety buffers based on daily sales velocity.

*Report generated by RetailPulse API v2.0*
"""
    return StreamingResponse(
        io.BytesIO(report.encode("utf-8")),
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=retailpulse_executive_report.md"},
    )
